services:
  - type: web
    name: better-call-zool-api
    env: node
    rootCommand: cd backend
    buildCommand: npm install
    startCommand: npm start
    plan: free
    envVars:
      - key: DB_HOST
        value: mysql-better-call-zool-better-call-zool-db.d.aivencloud.com
      - key: DB_USER
        value: avnadmin
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        value: defaultdb
      - key: DB_PORT
        value: 27940
      - key: JWT_SECRET
        value: supersecretkey123
      - key: PORT
        value: 3000

